global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'aura-core'
    static_configs:
      - targets: ['core-service:50051'] # This might not work if core-service doesn't expose metrics on gRPC port in a way prometheus likes
