apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-core"
spec:
  type: ClusterIP # Core service is internal only
  selector:
    app: core
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP