apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secrets"
type: Opaque
stringData:
  mistral-key: "{{ .Values.secrets.mistralApiKey }}"
  openai-key: "{{ .Values.secrets.openaiApiKey }}"
  telegram-token: "{{ .Values.secrets.telegramToken }}"