apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-telegram"
spec:
  replicas: {{ .Values.telegram.replicaCount }}
  selector:
    matchLabels:
      app: telegram
  template:
    metadata:
      labels:
        app: telegram
    spec:
      {{- with .Values.secrets.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: telegram
          image: "{{ .Values.telegram.image.repository }}:{{ .Values.telegram.image.tag }}"
          imagePullPolicy: {{ .Values.telegram.image.pullPolicy }}
          resources:
            {{ toYaml .Values.telegram.resources | nindent 12 }}
          env:
            - name: AURA_TG__TOKEN
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-secrets"
                  key: "telegram-token"
            - name: AURA_TG__CORE_URL
              value: "{{ .Release.Name }}-core:50051"
            - name: LOG_LEVEL
              value: "{{ .Values.telegram.env.LOG_LEVEL }}"
