apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-frpc-config"
data:
  frpc.toml: |
    serverAddr = "aura.zae.life"
    serverPort = 7000

    [auth]
    method = "token"

    [auth.tokenSource]
    type = "file"

    [auth.tokenSource.file]
    path = "/etc/frp/token"

    [[proxies]]
    name = "frontend"
    type = "tcp"
    localIP = "aura-frontend"
    localPort = 3000
    remotePort = 8081

    [[proxies]]
    name = "gateway"
    type = "tcp"
    localIP = "aura-gateway"
    localPort = 8000
    remotePort = 8082

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-frpc-tunnel"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frpc
  template:
    metadata:
      labels:
        app: frpc
    spec:
      containers:
      - name: frpc
        image: "{{ .Values.tunnel.image.repository }}:{{ .Values.tunnel.image.tag }}"
        imagePullPolicy: {{ .Values.tunnel.image.pullPolicy | default "IfNotPresent" }}
        volumeMounts:
        - name: config
          mountPath: /etc/frp/frpc.toml
          subPath: frpc.toml
        - name: token
          mountPath: /etc/frp/token
          subPath: token
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: "{{ .Release.Name }}-frpc-config"
      - name: token
        secret:
          secretName: "{{ .Release.Name }}-{{ .Values.secrets.frpClientToken.name }}"
          items:
          - key: token
            path: token
